# Generated by Django 4.2.6 on 2023-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hub_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('operating_hours', models.CharField(max_length=100)),
                ('hub_image', models.ImageField(upload_to='hubimages')),
                ('hub_types', models.CharField(choices=[('auto', 'Auto Repair'), ('towing', 'Towing'), ('bodyshop', 'Body Shop'), ('maintenance', 'Maintenance'), ('custom', 'Custom Work'), ('all', 'All'), ('others', 'Others')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('password', models.CharField(max_length=255)),
                ('accept_terms', models.BooleanField()),
            ],
        ),
    ]
