# Generated by Django 4.2.6 on 2023-11-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohub', '0002_remove_hubregistration_accept_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohub.hubregistration')),
            ],
        ),
    ]
