# Generated by Django 4.2.6 on 2023-11-23 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohub', '0004_remove_mechanic_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autohub.hubregistration'),
        ),
    ]
