# Generated by Django 4.2.6 on 2023-11-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0013_alter_userdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
    ]
